---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ingress
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      nodePort: 32000
    - port: 18080
      name: http-mgmt
  selector:
    app: nginx-ingress-lb