apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts: 
        - name: primeiro-pv
          mountPath: /volume-dentro-do-container
  volumes:
    - name: primeiro-pv
      persistentVolumeClaim:
        claimName: primeiro-pv-claim