apiVersion: v1
kind: PersistentVolume
metadata:
  name: primeiro-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: primeiro-volume
    fsType: ext4
  storageClassName: standard
  