apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistentvolume-mysql
  namespace: default
  labels:
    app: persistentvolume-mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-hostpath-sc